apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    meta.helm.sh/release-name: kafka
    meta.helm.sh/release-namespace: kafka
  creationTimestamp: "2024-11-13T15:32:46Z"
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: 3.9.0
    helm.sh/chart: kafka-31.0.0
  name: kafka
  namespace: kafka
  resourceVersion: "40736"
  uid: bf3c1b29-0a15-40ac-942f-d3c6093301a5
spec:
  clusterIP: 34.118.236.134
  clusterIPs:
  - 34.118.236.134
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-client
    port: 9092
    protocol: TCP
    targetPort: client
  - name: tcp-external
    port: 9095
    protocol: TCP
    targetPort: external
  selector:
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: kafka
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
