apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
  namespace: kafka
type: Opaque
data:
  KAFKA_USERNAME: dXNlcjE=  # Base64 encoded value of 'client'
  KAFKA_PASSWORD: QU9pVDg4YkNUQg==  # Base64 encoded value of the password