apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-spring-app
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-spring-app
  template:
    metadata:
      labels:
        app: kafka-spring-app
    spec:
      containers:
        - name: kafka-spring-app
          image: gcr.io/kafka-demo-441512/spring-kafka-example:latest
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-credentials
                  key: KAFKA_USERNAME
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-credentials
                  key: KAFKA_PASSWORD
          ports:
            - containerPort: 8080